title: <p align='center'>  Shalini Kushwaha </p>
logo: /assets/img/IMG20230703181346.jpg
description: <p align='center'>Recent graduate from Delhi University. <a herf='https://www.linkedin.com/in/shalini-k-0063681b8/'>Linkdin</a>|<a herf='https://github.com/itsshaliniS'>Github</a></p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: False
