#!/bin/sh
bundle install 

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem install jekyll-remote-theme
gem build jekyll-theme-minimal.gemspec
